/*
 * File: app/view/AddApiCodexampleWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rubedo.view.AddApiCodexampleWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.AddApiCodexampleWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    width: 586,
    title: 'Add code example',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Verb',
                            name: 'verb',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            editable: false,
                            forceSelection: true,
                            queryMode: 'local',
                            store: [
                                'get',
                                'put',
                                'post',
                                'delete',
                                'patch'
                            ]
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Type',
                            name: 'type',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            editable: false,
                            forceSelection: true,
                            queryMode: 'local',
                            store: [
                                'route',
                                'entity'
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Code',
                            name: 'code',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            rows: 14
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form=button.up().getForm();
                                if (form.isValid()){
                                    Ext.getStore("CodeExamples").add(form.getValues());
                                    button.up().up().close();
                                }
                            },
                            anchor: '100%',
                            text: 'Add'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});